// This file was autogenerated by D:\Work\GitHub\blogger.toc\lib\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/blogger/toc/main.js', ['garafu.blogger.toc.Main'], ['garafu.blogger.toc.Settings', 'garafu.blogger.toc.printer.LabelContentsOrderPrinter', 'garafu.blogger.toc.printer.LabelNameOrderPrinter', 'garafu.blogger.toc.printer.LabelPrinter', 'garafu.blogger.toc.printer.TitlePrinter', 'garafu.blogger.toc.sorter.PublishedDateSorter', 'garafu.blogger.toc.sorter.SortKey', 'garafu.blogger.toc.sorter.TitleNameSorter', 'garafu.blogger.toc.sorter.UpdatedDateSorter', 'garafu.date.W3CDTF', 'garafu.dom', 'garafu.events']);
goog.addDependency('../../../../src/blogger/toc/printer/Entry.js', ['garafu.blogger.toc.printer.Entry'], ['garafu.date.W3CDTF']);
goog.addDependency('../../../../src/blogger/toc/printer/abstractprinter.js', ['garafu.blogger.toc.printer.AbstractPrinter'], []);
goog.addDependency('../../../../src/blogger/toc/printer/category.js', ['garafu.blogger.toc.printer.Category'], []);
goog.addDependency('../../../../src/blogger/toc/printer/labelcontentsorderprinter.js', ['garafu.blogger.toc.printer.LabelContentsOrderPrinter'], ['garafu.blogger.toc.printer.LabelPrinter']);
goog.addDependency('../../../../src/blogger/toc/printer/labelnameorderprinter.js', ['garafu.blogger.toc.printer.LabelNameOrderPrinter'], ['garafu.blogger.toc.printer.LabelPrinter']);
goog.addDependency('../../../../src/blogger/toc/printer/labelprinter.js', ['garafu.blogger.toc.printer.LabelPrinter'], ['garafu.blogger.toc.printer.AbstractPrinter', 'garafu.blogger.toc.printer.Category', 'garafu.blogger.toc.printer.Entry']);
goog.addDependency('../../../../src/blogger/toc/printer/titleprinter.js', ['garafu.blogger.toc.printer.TitlePrinter'], ['garafu.blogger.toc.printer.AbstractPrinter', 'garafu.blogger.toc.printer.Entry']);
goog.addDependency('../../../../src/blogger/toc/settings.js', ['garafu.blogger.toc.Settings'], ['garafu.i18n.DateTimeFormat']);
goog.addDependency('../../../../src/blogger/toc/sorter/SortKey.js', ['garafu.blogger.toc.sorter.SortKey'], []);
goog.addDependency('../../../../src/blogger/toc/sorter/SortOrder.js', ['garafu.blogger.toc.sorter.SortOrder'], []);
goog.addDependency('../../../../src/blogger/toc/sorter/abstractsorter.js', ['garafu.blogger.toc.sorter.AbstractSorter'], []);
goog.addDependency('../../../../src/blogger/toc/sorter/publisheddatesorter.js', ['garafu.blogger.toc.sorter.PublishedDateSorter'], ['garafu.blogger.toc.sorter.AbstractSorter', 'garafu.blogger.toc.sorter.SortOrder']);
goog.addDependency('../../../../src/blogger/toc/sorter/titlenamesorter.js', ['garafu.blogger.toc.sorter.TitleNameSorter'], ['garafu.blogger.toc.sorter.AbstractSorter', 'garafu.blogger.toc.sorter.SortOrder']);
goog.addDependency('../../../../src/blogger/toc/sorter/updateddatesorter.js', ['garafu.blogger.toc.sorter.UpdatedDateSorter'], ['garafu.blogger.toc.sorter.AbstractSorter', 'garafu.blogger.toc.sorter.SortOrder']);
goog.addDependency('../../../../src/date/W3CDTF.js', ['garafu.date.W3CDTF'], ['garafu.string']);
goog.addDependency('../../../../src/dom/dom.js', ['garafu.dom'], []);
goog.addDependency('../../../../src/events/events.js', ['garafu.events'], []);
goog.addDependency('../../../../src/i18n/DateTimeFormat.js', ['garafu.i18n.DateTimeFormat'], ['garafu.i18n.DateTimeSymbols', 'garafu.string']);
goog.addDependency('../../../../src/i18n/DateTimeSymbols.js', ['garafu.i18n.DateTimeSymbols'], []);
goog.addDependency('../../../../src/string/string.js', ['garafu.string'], []);
